build_ex00:
	cd cmd/app/loadingData && go build -o ../../../bin

start_ex00:
	./bin/loadingData


build_ex01:
	cd cmd/app/simplestInterface && go build -o ../../../bin

start_ex01:
	./bin/simplestInterface


build_ex02:
	cd cmd/app/properAPI && go build -o ../../../bin

start_ex02:
	./bin/properAPI


build_ex03:
	cd cmd/app/closestRestaurants && go build -o ../../../bin

start_ex03:
	./bin/closestRestaurants


build_ex04:
	cd cmd/app/JWT && go build -o ../../../bin

start_ex04:
	./bin/JWT


clean:
	cd bin/ && rm -rf *
